schema_version: 1

context:
  version: 1.8.8

package:
  name: libfind
  version: ${{ version }}

source:
  # url: https://github.com/FSSlc/LibFind/archive/refs/tags//v{{ version }}.tar.gz
  # file_name: libfind-${{ version }}.tar.gz
  path: ..

build:
  number: 0
  noarch: generic

requirements:
  run:
    - cmake >=3.12

about:
  license: MIT
  summary: Tool for analyzing includes in C++.
  description: |
    A collection of cmake helpers for SCNS.
  homepage: https://github.com/FSSlc/LibFind
  documentation: https://github.com/FSSlc/LibFind

extra:
  recipe-maintainers:
    - fsslc

